//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdilliaKP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OlgaZuravlevaEntities : DbContext
    {
        private static OlgaZuravlevaEntities _context;
        public static OlgaZuravlevaEntities GetContext()
        {
            if (_context == null)
            {
                _context = new OlgaZuravlevaEntities();
            }
            return _context;
        }
        public OlgaZuravlevaEntities()
            : base("name=OlgaZuravlevaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Dishes> Dishes { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderAndSale> OrderAndSale { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
    }
}
