//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdilliaKP
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAndSale
    {
        public int ID_OrderAndSale { get; set; }
        public int ID_Dishes { get; set; }
        public int ID_Order { get; set; }
        public double Summ { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Order Order { get; set; }
    }
}
